# Generated by Django 4.2.20 on 2025-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.CharField(default='someuserid', max_length=100),
            preserve_default=False,
        ),
    ]
